//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austin.PBConsoleFrontend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Austin.PBConsoleFrontend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; --------------------------------------------------------------------
        ///; - Generic PicoBlaze/Nexys Starter File for Mediatronix PicoBlaze
        ///; - and KCPSM3 assembler. See the notes listed below. 
        ///; --------------------------------------------------------------------
        ///; --------------------------------------------------------------------
        ///; - Assembler Directives
        ///; --------------------------------------------------------------------
        ///; These are for the KCPSM3 assembler I/O port addressing
        ///; COMMENT these  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Austin_Prog_ROM {
            get {
                return ResourceManager.GetString("Austin_Prog_ROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,1C
        ///B,32
        ///C,21
        ///D,23
        ///E,24
        ///F,2B
        ///G,34
        ///H,33
        ///I,43
        ///J,3B
        ///K,42
        ///L,4B
        ///M,3A
        ///N,31
        ///O,44
        ///P,4D
        ///Q,15
        ///R,2D
        ///S,1B
        ///T,2C
        ///U,3C
        ///V,2A
        ///W,1D
        ///X,22
        ///Y,35
        ///Z,1A
        ///D0,45
        ///D1,16
        ///D2,1E
        ///D3,26
        ///D4,25
        ///D5,2E
        ///D6,36
        ///D7,3D
        ///D8,3E
        ///D9,46
        ///OemMinus,4E
        ///Subtract,4E
        ///Back,66
        ///Space,29
        ///Tab,0D
        ///Enter,5A
        ///Escape,76
        ///F1,5
        ///F2,6
        ///F3,4
        ///F4,0C
        ///F5,3
        ///F6,0B
        ///F7,83
        ///F8,0A
        ///F9,1
        ///F10,9
        ///F11,78
        ///F12,7
        ///Up,75
        ///Left,6B
        ///Down,72
        ///Right,74.
        /// </summary>
        internal static string KeysToScan {
            get {
                return ResourceManager.GetString("KeysToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; --------------------------------------------------------------------
        ///; - Generic PicoBlaze/Nexys Starter File for Mediatronix PicoBlaze
        ///; - and KCPSM3 assembler. See the notes listed below. 
        ///; --------------------------------------------------------------------
        ///; --------------------------------------------------------------------
        ///; - Assembler Directives
        ///; --------------------------------------------------------------------
        ///; These are for the KCPSM3 assembler I/O port addressing
        ///; COMMENT these  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prog_Rom {
            get {
                return ResourceManager.GetString("Prog_Rom", resourceCulture);
            }
        }
    }
}
