//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Austin.PicoCompile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Austin.PicoCompile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to component_name={name};
        ///width_a=18;
        ///depth_a=1024;
        ///configuration_port_a=read_only;
        ///port_a_enable_pin=false;
        ///port_a_handshaking_pins=false;
        ///port_a_register_inputs=false;
        ///port_a_init_pin=false;
        ///port_a_init_value=00000;
        ///port_a_additional_output_pipe_stages = 0;
        ///port_a_register_inputs = false;
        ///port_a_active_clock_edge = Rising_Edge_Triggered;
        ///width_b=18;
        ///depth_b=1024;
        ///configuration_port_b=read_and_write;
        ///write_mode_port_b=read_after_write;
        ///port_b_enable_pin=false;
        ///port_b_handshaking_pins=false;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ROM_form_coe {
            get {
                return ResourceManager.GetString("ROM_form_coe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ////////////////////////////////////////////////////////////////////////////////
        ///// Copyright (c) 2004 Xilinx, Inc.
        ///// All Rights Reserved
        ///////////////////////////////////////////////////////////////////////////////////
        /////   ____  ____
        /////  /   /\/   /
        ///// /___/  \  /    Vendor: Xilinx
        ///// \   \   \/     Version: 1.02
        /////  \   \         Filename: ROM_form.v
        /////  /   /         Date Last Modified:  September 7 2004
        ///// /___/   /\     Date Created: July 2003
        ///// \   \  /  \
        /////  \___\/\___\
        /////
        /////Device:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ROM_form_v {
            get {
                return ResourceManager.GetString("ROM_form_v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM_form.vhd
        ///
        ///Ken Chapman (Xilinx Ltd) July 2003
        ///Minor modifications by Austin Wise December 2009
        ///
        ///This is the VHDL template file for the KCPSM3 assembler.
        ///It is used to configure a Spartan-3, Virtex-II or Virtex-IIPRO block RAM to act as 
        ///a single port program ROM.
        ///
        ///This VHDL file is not valid as input directly into a synthesis or simulation tool.
        ///The assembler will read this template and insert the data required to complete the 
        ///definition of program ROM and write it out to a new &apos;.vhd&apos; file as [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ROM_form_vhd {
            get {
                return ResourceManager.GetString("ROM_form_vhd", resourceCulture);
            }
        }
    }
}
